const unit1Words=[
['professional','ADJECTIVE','earning money from a skilled activity','a professional athlete','I would be famous as one of the first professional female squash players in the Middle East.','A professional takes practice seriously.'],
['Little did I know that…','PHRASE','used to say that you did not know what would happen later','Little did I know that…','Little did I know that ten years later I would be famous as one of the first professional female squash players in the Middle East!','Little did I know that this small choice would change my life.'],
['unfamiliar','ADJECTIVE','not known or recognised','be unfamiliar with something','For those of you who are unfamiliar with squash, it is not like tennis or badminton.','The new school felt unfamiliar at first.'],
['opponent','NOUN','the person you compete against','a strong opponent','The aim of the game is to hit the ball in such a way that your opponent cannot return it.','She shook hands with her opponent after the match.'],
['mentally and physically intense','PHRASE','requiring a lot of effort from your mind and body','a mentally and physically intense sport','Because it was mentally and physically intense, I never got bored.','The final was mentally and physically intense.'],
['defeat','NOUN','a failure to win','suffer a defeat','I went from playing squash for fun to becoming a real force on the court after suffering several defeats.','The team learned from the defeat.'],
['be determined to do','PHRASE','to have a strong decision to do something','be determined to improve','I was determined to get better, so I joined a local tournament at my gym.','He is determined to finish the project.'],
['loads of','PHRASE','a lot of','loads of games','I lost loads of games, and I was really disappointed.','There are loads of ways to practise vocabulary.'],
['disappointed','ADJECTIVE','sad because something was not as good as expected','feel disappointed','I lost loads of games, and I was really disappointed.','She felt disappointed by her test result.'],
['make a promise to myself','PHRASE','to make a serious personal decision','make a promise to myself to improve','I made a promise to myself that I would keep trying to improve.','I made a promise to myself to read every day.'],
['movements','NOUN','actions made by the body','learn particular movements','This pushed me into learning particular movements and the finer techniques of the game.','The coach showed us the correct movements.'],
['compete with','VERB','to try to win against someone','compete with other players','Opportunities to compete with other female players were particularly limited.','Small teams can compete with bigger clubs.'],
['limited','ADJECTIVE','small in amount or number','limited opportunities','Opportunities to compete with other female players were particularly limited.','We have limited time before the exam.'],
['discipline','NOUN','self-control and steady training','require discipline','Today, my training has to follow a system, so it requires a great deal of discipline.','Learning a language requires discipline.'],
['goal-oriented','ADJECTIVE','focused on achieving clear aims','a goal-oriented style','I have a goal-oriented style, and I’m like that at work too.','A goal-oriented student checks progress each week.'],
['set goals for myself','PHRASE','decide what I want to achieve','set goals for myself','I set goals for myself and really work hard to achieve them.','I set goals for myself at the start of each term.'],
['achieve','VERB','successfully reach a goal','achieve a goal','I set goals for myself and really work hard to achieve them.','You can achieve more with a clear plan.'],
['elite','ADJECTIVE','among the best in a group','elite international players','I had the opportunity not only to meet elite international players, but also to actually get on a court with some of the world’s best players.','Only elite athletes reach this final.'],
['completely','ADVERB','totally; in every way','completely overwhelming','This was a completely overwhelming experience – and one that I’ll never forget!','The room was completely silent.'],
['overwhelming','ADJECTIVE','very powerful or difficult to deal with','an overwhelming experience','This was a completely overwhelming experience – and one that I’ll never forget!','The amount of homework felt overwhelming.'],
['inspire','VERB','make someone want to do something positive','inspire the next generation','I hope my success will inspire the next generation of women athletes.','Her courage continues to inspire me.'],
['generation','NOUN','people born and living at about the same time','the next generation','I hope my success will inspire the next generation of women athletes.','This generation learns with digital tools.'],
['hence','ADVERB','for this reason','hence, a new challenge','They needed a new challenge – hence, speedcubing was born.','The road was closed; hence, we took a train.'],
['regardless','ADVERB','without being affected by something','regardless of speed','Everybody is welcome, regardless of speed.','She kept practising regardless of the weather.'],
['feat','NOUN','an impressive achievement','a massive feat','Being able to solve the cube is not a massive feat.','Running a marathon is an amazing feat.'],
['monetary','ADJECTIVE','related to money','monetary demands','The monetary demands are fairly low – but time and patience are key.','The club offers no monetary reward.'],
['pastime','NOUN','an activity done for enjoyment','an entertaining pastime','The Rubik’s Cube has been an entertaining pastime for millions.','Reading is my favourite pastime.'],
['devote…to…','VERB','give a lot of time or effort to something','devote your life to something','Some have devoted their lives to this, and worked hard to discover the minimum number of moves required to solve the cube.','She devotes an hour to reading each night.'],
['decade','NOUN','a period of ten years','over a decade','Little did I know that ten years later…','The club has grown over the past decade.'],
['competitor','NOUN','a person who takes part in a competition','a fast competitor','Nineteen competitors, each the fastest solver in their own country, were invited to compete.','Every competitor received a certificate.'],
['competition','NOUN','an organised event in which people try to win','enter a competition','The first competition is always the most worrying.','Our school held a speaking competition.'],
['have a go','PHRASE','try something','have a go at speedcubing','Anyone can have a go.','Have a go at using the new word in a sentence.'],
['demand','NOUN','the amount of money, time or effort needed','monetary demands','The monetary demands are fairly low – but time and patience are key.','The course makes heavy demands on your time.'],
['patience','NOUN','the ability to wait calmly','time and patience','Time and patience are key.','Solving the cube takes patience.'],
['put off','PHRASAL VERB','delay doing something','put off by something','Don’t be put off by the word “competition” – everybody is welcome.','Do not put off your revision until Sunday.'],
['massive','ADJECTIVE','very large or important','a massive feat','Being able to solve the cube is not a massive feat.','The project was a massive success.'],
['atmosphere','NOUN','the feeling or mood of a place','an incredible atmosphere','Nevertheless, the atmosphere is incredible, and it is something everybody should experience.','The friendly atmosphere helped me relax.'],
['incredible','ADJECTIVE','extremely good or impressive','an incredible atmosphere','The atmosphere is incredible, and it is something everybody should experience.','She gave an incredible performance.']
];
const unit2Words=[
['digital','ADJECTIVE','using computer technology or electronic systems','digital devices','Some people may say that I’m online too much and that my digital devices control my life, but my response is that they make my life better and easier.','Digital tools make it easier to share ideas with classmates.'],
['entertainment','NOUN','activities that amuse or interest people','digital entertainment','All my life I’ve never had a television in my home, and certainly no other form of digital entertainment.','Music is my favourite form of entertainment after school.'],
['retired','ADJECTIVE','no longer working because of age','be retired','I’m retired now, but when I was a kid my parents couldn’t afford to buy a television, or even a radio.','My retired neighbour volunteers at the library.'],
['afford','VERB','have enough money to pay for something','afford to buy','My parents couldn’t afford to buy a television, or even a radio.','We cannot afford to waste time before the exam.'],
['priority','NOUN','something that is more important than other things','make something a priority','Having a television just wasn’t a priority.','Safety is our top priority during the trip.'],
['queue','NOUN','a line of people waiting for something','wait in a queue','I even take a book with me when I go shopping or to the bank, just in case I have to wait in a queue.','People formed a queue outside the cinema.'],
['issue','NOUN','an important problem or topic','not be an issue','So for me a home without a television just isn’t an issue.','The broken printer is not an issue anymore.'],
['educator','NOUN','a person or thing that teaches','an online educator','For me, the internet is an educator above everything else.','A good teacher is an educator and a role model.'],
['access','NOUN','the right or opportunity to use or reach something','have access to','We are incredibly lucky to have access to so much high-quality educational content.','Students need access to reliable information.'],
['content','NOUN','the information or material in a book, website or programme','educational content','We are incredibly lucky to have access to so much high-quality educational content.','The website provides useful science content.'],
['incredibly','ADVERB','in a very great or extreme way','incredibly lucky','We are incredibly lucky to have access to so much high-quality educational content.','The puzzle was incredibly difficult.'],
['current','ADJECTIVE','happening or existing now','current affairs','There really is also no excuse not to be well-informed about current affairs.','We discussed current events in class.'],
['affair','NOUN','an event or subject, especially one involving public interest','current affairs','There really is also no excuse not to be well-informed about current affairs.','She reads about international affairs every morning.'],
['well-informed','ADJECTIVE','knowing a lot about a subject','be well-informed about','There really is also no excuse not to be well-informed about current affairs.','A well-informed voter checks several sources.'],
['available','ADJECTIVE','ready to be used or obtained','readily available','With so much free content readily available, we are definitely spoilt for choice.','The teacher made extra practice materials available online.'],
['definitely','ADVERB','without doubt; certainly','definitely spoilt for choice','We are definitely spoilt for choice, and we can’t use money as an excuse not to watch.','I will definitely revise these words tonight.'],
['complain','VERB','say that something is wrong or unsatisfactory','complain about','Those people who can only complain about the quality of programmes available should look a little deeper online.','It is better to solve a problem than simply complain about it.'],
['celebrity','NOUN','a famous person, especially in entertainment or sport','a celebrity chef','I recently watched a cooking programme with a celebrity chef.','The celebrity spoke to students about hard work.'],
['advise','VERB','tell someone what you think they should do','advise someone to do something','He also promoted his new book, advising everyone to buy it.','The librarian advised me to choose a shorter novel.'],
['essential','ADJECTIVE','completely necessary or very important','essential to','They are essential to my lifestyle, from the moment I wake up until I go to bed.','Sleep is essential to learning well.'],
['admit','VERB','say that something is true, often unwillingly','admit that','I have no problem in admitting this.','He had to admit that he had forgotten his homework.']
];
const fallbackUnits=[
{id:1,title:'Unit 1 · Sports and Free Time',subtitle:'Two stories about squash and speedcubing.',words:unit1Words.map((x,i)=>({word:x[0],pos:x[1],definition:x[2],collocation:x[3],sourceExample:x[4],example:x[5],image:i<22?'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=80':'https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=900&q=80'}))},
{id:2,title:'Unit 2 · Digital Age',subtitle:'Read and think critically about digital entertainment and information.',words:unit2Words.map(x=>({word:x[0],pos:x[1],definition:x[2],collocation:x[3],sourceExample:x[4],example:x[5],image:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80'}))}
];
let units=[...fallbackUnits],currentUnit,currentName,wordIndex=0,learnStarted=0,timerId,attemptNo=0,quizItems=[];const API_BASE='https://wordsprint-gsvl.onrender.com';const $=id=>document.getElementById(id);const show=id=>{document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));$(id).classList.remove('hidden');window.scrollTo(0,0)};async function api(path,options){try{const r=await fetch(`${API_BASE}${path}`,options);if(!r.ok)throw 0;return await r.json()}catch(_){return null}}
function populateUnits(){$('unitSelect').innerHTML=units.map(u=>`<option value="${u.id}">${u.title}</option>`).join('')}
function renderCard(){const w=currentUnit.words[wordIndex];$('learnUnitNo').textContent=String(currentUnit.id).padStart(2,'0');$('learnTitle').textContent=currentUnit.title;$('learnSubtitle').textContent=currentUnit.subtitle||'';$('learnProgress').textContent=`${wordIndex+1} / ${currentUnit.words.length}`;$('wordCount').textContent=currentUnit.words.length;$('cardPos').textContent=w.pos||'WORD';$('cardWord').textContent=w.word;$('cardDefinition').textContent=w.definition;$('cardCollocation').textContent=w.collocation;$('cardExample').textContent=`“${w.sourceExample}”\n\nHelpful example: ${w.example}`;$('cardImage').style.backgroundImage=`url("${w.image}")`;$('wordDots').innerHTML=currentUnit.words.map((_,i)=>`<i class="${i===wordIndex?'active':''}"></i>`).join('');$('prevWord').disabled=wordIndex===0;$('nextWord').disabled=wordIndex===currentUnit.words.length-1;$('wordCard').classList.remove('flipped')}
function startLearning(){currentName=$('studentName').value.trim();if(!currentName){$('studentName').focus();return}currentUnit=units.find(u=>String(u.id)===$('unitSelect').value)||units[0];wordIndex=0;learnStarted=Date.now();$('sessionPill').textContent=currentName;$('sessionPill').classList.remove('hidden');renderCard();show('learnView')}
function buildQuiz(){const words=currentUnit.words;quizItems=words.slice(0,5).map(w=>{const options=[w.word,...words.filter(x=>x.word!==w.word).map(x=>x.word).slice(0,2)].sort(()=>Math.random()-.5);return{answer:w.word,prompt:w.example.replace(w.word,'_____'),options}});$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><div class="options">${q.options.map(o=>`<label><input type="radio" name="q${i}" value="${o}">${o}</label>`).join('')}</div></div>`).join('');$('quizProgressText').textContent=`0 / ${quizItems.length} answered`;$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}
function updateQuizProgress(){const a=quizItems.map((_,i)=>document.querySelector(`input[name=q${i}]:checked`));const done=a.filter(Boolean).length;$('quizProgressText').textContent=`${done} / ${quizItems.length} answered`;$('quizProgressBar').style.width=`${done/quizItems.length*100}%`};function formatTime(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
async function submitQuiz(){const a=quizItems.map((_,i)=>document.querySelector(`input[name=q${i}]:checked`));if(a.some(x=>!x)){$('quizHint').textContent='Please answer every question first.';return}clearInterval(timerId);const correct=a.reduce((n,x,i)=>n+(x.value===quizItems[i].answer?1:0),0),score=Math.round(correct/quizItems.length*100),seconds=Math.floor((Date.now()-learnStarted)/1000),record={name:currentName,unit:currentUnit.title,score,total:100,seconds,attempt:++attemptNo,passed:score>=70};const saved=await api('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});if(!saved){const all=JSON.parse(localStorage.getItem('wordSprintAttempts')||'[]');all.unshift({...record,at:new Date().toLocaleString()});localStorage.setItem('wordSprintAttempts',JSON.stringify(all))}$('resultIcon').textContent=score>=70?'✓':'!';$('resultKicker').textContent=score>=70?'UNIT PASSED':'KEEP PRACTISING';$('resultTitle').textContent=score>=70?'You passed this round.':'Keep practising and try again.';$('resultScore').textContent=score;$('resultMessage').textContent=score>=70?`${currentName}, you have mastered this round's focus words.`:`You got ${correct} / ${quizItems.length}. You need 70 points to pass.`;document.querySelector('.result-panel').classList.toggle('fail',score<70);show('resultView')}
async function loadTeacher(){const data=await api('/api/attempts');renderTeacher(data||JSON.parse(localStorage.getItem('wordSprintAttempts')||'[]'))}function renderTeacher(rows){const students=new Set(rows.map(r=>r.name)).size,avg=rows.length?Math.round(rows.reduce((a,r)=>a+Number(r.score),0)/rows.length):0,passed=rows.length?Math.round(rows.filter(r=>r.score>=70).length/rows.length*100):0;$('metricStudents').textContent=students;$('metricScore').textContent=avg;$('metricPass').textContent=`${passed}%`;$('resultsTable').innerHTML=rows.length?`<table><thead><tr><th>Student</th><th>Unit</th><th>Score</th><th>Time</th><th>Result</th><th>Submitted</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${r.name}</td><td>${r.unit}</td><td>${r.score}/100</td><td>${formatTime(r.seconds)}</td><td class="${r.score>=70?'pass':'fail'}">${r.score>=70?'Passed':'Not passed'}</td><td>${r.submitted_at||r.at||''}</td></tr>`).join('')}</tbody></table>`:'<p class="privacy-note">No study records yet.</p>'}
async function addUnit(){const title=$('newUnitTitle').value.trim(),raw=$('newUnitWords').value.split(/[,\n]/).map(x=>x.trim()).filter(Boolean);if(!title||raw.length<20){$('unitMessage').textContent='Add a title and at least 20 words.';return}const words=raw.map(word=>({word,pos:'WORD',definition:`a useful word to learn in ${title}`,collocation:`use ${word} in context`,sourceExample:`The word ${word} appears in this unit.`,example:`I can use the word ${word} in a sentence.`,image:'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=900&q=80'})),unit={id:Date.now(),title,subtitle:'A new word set created by Julia Yuan.',words},saved=await api('/api/units',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(unit)});units.push(saved||unit);populateUnits();$('unitMessage').textContent='Unit created. Students can study it now.';$('newUnitTitle').value='';$('newUnitWords').value=''}
document.addEventListener('change',e=>{if(e.target.matches('input[type=radio]'))updateQuizProgress()});$('startBtn').onclick=startLearning;$('wordCard').onclick=()=>$('wordCard').classList.toggle('flipped');$('prevWord').onclick=()=>{if(wordIndex>0){wordIndex--;renderCard()}};$('nextWord').onclick=()=>{if(wordIndex<currentUnit.words.length-1){wordIndex++;renderCard()}};$('finishLearn').onclick=()=>{buildQuiz();show('quizView')};$('exitLearn').onclick=()=>show('welcomeView');$('submitQuiz').onclick=submitQuiz;$('retryBtn').onclick=()=>{buildQuiz();show('quizView')};$('backHomeBtn').onclick=()=>{attemptNo=0;show('welcomeView')};$('teacherBtn').onclick=async()=>{const password=prompt('Teacher password (demo: change-me)');if(password!=='change-me')return alert('Incorrect password');show('teacherView');loadTeacher()};$('closeTeacher').onclick=()=>show('welcomeView');$('refreshTeacher').onclick=loadTeacher;$('addUnitBtn').onclick=addUnit;(async()=>{const data=await api('/api/units');if(data&&data.length)units=[...fallbackUnits,...data.filter(u=>u.id!==1)];populateUnits()})();

// Teacher-editable content and the 20-question checkpoint.
function renderCard(){const w=currentUnit.words[wordIndex];$('learnUnitNo').textContent=String(currentUnit.id).padStart(2,'0');$('learnTitle').textContent=currentUnit.title;$('learnSubtitle').textContent=currentUnit.subtitle||'';$('learnProgress').textContent=`${wordIndex+1} / ${currentUnit.words.length}`;$('wordCount').textContent=currentUnit.words.length;$('cardPos').textContent=w.pos||'WORD';$('cardWord').textContent=w.word;$('cardDefinition').textContent=w.definition;$('cardCollocation').textContent=w.collocation;$('cardSourceExample').textContent=w.sourceExample||'';$('cardHelpfulExample').textContent=w.example||'';$('cardImage').style.backgroundImage=`url("${w.image}")`;$('wordDots').innerHTML=currentUnit.words.map((_,i)=>`<i class="${i===wordIndex?'active':''}"></i>`).join('');$('prevWord').disabled=wordIndex===0;$('nextWord').disabled=wordIndex===currentUnit.words.length-1;$('wordCard').classList.remove('flipped')}
function buildQuiz(){const words=currentUnit.words;if(words.length<20){$('quizHint').textContent='This unit needs at least 20 words for the checkpoint.';return}quizItems=words.slice(0,20).map(w=>{const options=[w.word,...words.filter(x=>x.word!==w.word).sort(()=>Math.random()-.5).slice(0,3).map(x=>x.word)].sort(()=>Math.random()-.5);return{answer:w.word,prompt:(w.example||w.sourceExample||'').replace(w.word,'_____'),options}});$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><div class="options">${q.options.map(o=>`<label><input type="radio" name="q${i}" value="${o}">${o}</label>`).join('')}</div></div>`).join('');$('quizProgressText').textContent=`0 / ${quizItems.length} answered`;$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}
function populateEditor(){if(!$('editUnitSelect'))return;$('editUnitSelect').innerHTML=units.map(u=>`<option value="${u.id}">${u.title}</option>`).join('');loadEditorUnit()}
function loadEditorUnit(){const u=units.find(x=>String(x.id)===$('editUnitSelect').value)||units[0];$('editWordSelect').innerHTML=u.words.map((w,i)=>`<option value="${i}">${i+1}. ${w.word}</option>`).join('');loadEditorWord()}
function loadEditorWord(){const u=units.find(x=>String(x.id)===$('editUnitSelect').value)||units[0],w=u.words[Number($('editWordSelect').value)||0];if(!w)return;$('editImage').value=w.image||'';$('editCollocation').value=w.collocation||'';$('editSourceExample').value=w.sourceExample||'';$('editHelpfulExample').value=w.example||''}
async function saveWord(){const u=units.find(x=>String(x.id)===$('editUnitSelect').value),w=u.words[Number($('editWordSelect').value)||0];w.image=$('editImage').value.trim();w.collocation=$('editCollocation').value.trim();w.sourceExample=$('editSourceExample').value.trim();w.example=$('editHelpfulExample').value.trim();const saved=await api('/api/units',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(u)});if(saved){const idx=units.findIndex(x=>x.id===u.id);units[idx]=saved}$('editMessage').textContent='Saved. Students will see the updated card next round.';if(currentUnit&&currentUnit.id===u.id)renderCard()}
document.addEventListener('change',e=>{if(e.target.id==='editUnitSelect')loadEditorUnit();if(e.target.id==='editWordSelect')loadEditorWord()});$('saveWordBtn').onclick=saveWord;const oldTeacher=$('teacherBtn').onclick;$('teacherBtn').onclick=async()=>{const password=prompt('Teacher password (demo: change-me)');if(password!=='change-me')return alert('Incorrect password');show('teacherView');populateEditor();loadTeacher()};// Demo access: the console is local to this prototype; add account authentication before deployment.
$('teacherBtn').onclick=()=>{show('teacherView');populateEditor();loadTeacher()};

function imageForWord(word){const w=word.toLowerCase();if(/squash|opponent|compete|competitor|competition|athlete|professional|elite|defeat|movements/.test(w))return 'https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=900&q=80';if(/cube|pastime|feat|have a go|put off/.test(w))return 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?auto=format&fit=crop&w=900&q=80';if(/money|monetary|demand/.test(w))return 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?auto=format&fit=crop&w=900&q=80';if(/generation|inspire|goal|achieve|determined|discipline|decade/.test(w))return 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=900&q=80';if(/patience|patient|limited|unfamiliar|disappointed|overwhelming/.test(w))return 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=80';if(/atmosphere|incredible|massive|completely/.test(w))return 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=900&q=80';return 'https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=900&q=80'}
units.forEach(u=>u.words.forEach(w=>{w.image=imageForWord(w.word)}));
function buildQuiz(){const words=[...currentUnit.words].sort(()=>Math.random()-.5).slice(0,20);quizItems=words.map(w=>({answer:w.word,prompt:(w.example||w.sourceExample||'').replace(w.word,'_____')}));const bank=words.map(w=>w.word);$('wordBank').innerHTML=bank.map(w=>`<span class="bank-word">${w}</span>`).join('');$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><select class="answer-select" name="q${i}"><option value="">Choose a word from the bank</option>${bank.map(w=>`<option value="${w}">${w}</option>`).join('')}</select></div>`).join('');$('quizProgressText').textContent='0 / 20 answered';$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}
function updateQuizProgress(){const a=quizItems.map((_,i)=>document.querySelector(`select[name=q${i}]`));const done=a.filter(x=>x&&x.value).length;$('quizProgressText').textContent=`${done} / 20 answered`;$('quizProgressBar').style.width=`${done/20*100}%`}
async function submitQuiz(){const a=quizItems.map((_,i)=>document.querySelector(`select[name=q${i}]`));if(a.some(x=>!x||!x.value)){$('quizHint').textContent='Please answer every question first.';return}if(new Set(a.map(x=>x.value)).size!==20){$('quizHint').textContent='Use each word from the bank once.';return}clearInterval(timerId);const correct=a.reduce((n,x,i)=>n+(x.value===quizItems[i].answer?1:0),0),score=Math.round(correct/20*100),seconds=Math.floor((Date.now()-learnStarted)/1000),record={name:currentName,unit:currentUnit.title,score,total:100,seconds,attempt:++attemptNo,passed:score>=70};const saved=await api('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});if(!saved){const all=JSON.parse(localStorage.getItem('wordSprintAttempts')||'[]');all.unshift({...record,at:new Date().toLocaleString()});localStorage.setItem('wordSprintAttempts',JSON.stringify(all))}$('resultIcon').textContent=score>=70?'✓':'!';$('resultKicker').textContent=score>=70?'UNIT PASSED':'KEEP PRACTISING';$('resultTitle').textContent=score>=70?'You passed this round.':'Keep practising and try again.';$('resultScore').textContent=score;$('resultMessage').textContent=score>=70?`${currentName}, you have mastered this round's focus words.`:`You got ${correct} / 20. You need 70 points to pass.`;document.querySelector('.result-panel').classList.toggle('fail',score<70);show('resultView')}
document.addEventListener('change',e=>{if(e.target.matches('.answer-select'))updateQuizProgress()});
// Final learning card and typed-answer checkpoint behavior.
function renderCard(){const w=currentUnit.words[wordIndex];$('learnUnitNo').textContent=String(currentUnit.id).padStart(2,'0');$('learnTitle').textContent=currentUnit.title;$('learnSubtitle').textContent=currentUnit.subtitle||'';$('learnProgress').textContent=`${wordIndex+1} / ${currentUnit.words.length}`;$('wordCount').textContent=currentUnit.words.length;$('cardPos').textContent=w.pos||'WORD';$('cardWord').textContent=w.word;$('cardDefinition').textContent=w.definition;$('cardCollocation').textContent=w.collocation;$('cardSourceExample').textContent=w.sourceExample||'';$('cardHelpfulExample').textContent=w.example||'';$('wordDots').innerHTML=currentUnit.words.map((_,i)=>`<i class="${i===wordIndex?'active':''}"></i>`).join('');$('prevWord').disabled=wordIndex===0;$('nextWord').disabled=wordIndex===currentUnit.words.length-1;$('wordCard').classList.remove('flipped')}
function buildQuiz(){const words=[...currentUnit.words].sort(()=>Math.random()-.5).slice(0,20);quizItems=words.map(w=>({answer:w.word,prompt:(w.example||w.sourceExample||'').replace(w.word,'_____')}));$('wordBank').innerHTML=words.map(w=>`<span class="bank-word">${w.word}</span>`).join('');$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><input class="answer-input" name="q${i}" autocomplete="off" spellcheck="false" placeholder="Type the missing word"></div>`).join('');$('quizProgressText').textContent='0 / 20 answered';$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}
function updateQuizProgress(){const a=quizItems.map((_,i)=>document.querySelector(`input[name=q${i}]`));const done=a.filter(x=>x&&x.value.trim()).length;$('quizProgressText').textContent=`${done} / 20 answered`;$('quizProgressBar').style.width=`${done/20*100}%`}
function normAnswer(s){return s.toLowerCase().replace(/[’']/g,"'").replace(/\s+/g,' ').trim()}
async function submitQuiz(){const a=quizItems.map((_,i)=>document.querySelector(`input[name=q${i}]`));if(a.some(x=>!x||!x.value.trim())){$('quizHint').textContent='Please answer every question first.';return}if(new Set(a.map(x=>normAnswer(x.value))).size!==20){$('quizHint').textContent='Use each word from the bank once.';return}clearInterval(timerId);const correct=a.reduce((n,x,i)=>n+(normAnswer(x.value)===normAnswer(quizItems[i].answer)?1:0),0),score=Math.round(correct/20*100),seconds=Math.floor((Date.now()-learnStarted)/1000),record={name:currentName,unit:currentUnit.title,score,total:100,seconds,attempt:++attemptNo,passed:score>=70};const saved=await api('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});if(!saved){const all=JSON.parse(localStorage.getItem('wordSprintAttempts')||'[]');all.unshift({...record,at:new Date().toLocaleString()});localStorage.setItem('wordSprintAttempts',JSON.stringify(all))}$('resultIcon').textContent=score>=70?'✓':'!';$('resultKicker').textContent=score>=70?'UNIT PASSED':'KEEP PRACTISING';$('resultTitle').textContent=score>=70?'You passed this round.':'Keep practising and try again.';$('resultScore').textContent=score;$('resultMessage').textContent=score>=70?`${currentName}, you have mastered this round's focus words.`:`You got ${correct} / 20. You need 70 points to pass.`;document.querySelector('.result-panel').classList.toggle('fail',score<70);show('resultView')}
document.addEventListener('input',e=>{if(e.target.matches('.answer-input'))updateQuizProgress()});$('speakWord').onclick=e=>{e.stopPropagation();if('speechSynthesis' in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance($('cardWord').textContent);u.lang='en-US';u.rate=.86;speechSynthesis.speak(u)}};
// Use an English (UK) voice when the browser provides one.
function speakCurrentWord(){if(!('speechSynthesis' in window))return;speechSynthesis.cancel();const speak=()=>{const voices=speechSynthesis.getVoices();const british=voices.filter(v=>/^en-GB/i.test(v.lang));const female=british.find(v=>/female|susan|kate|serena|hazel|libby|samantha/i.test(v.name));const voice=female||british[0]||voices.find(v=>/^en/i.test(v.lang));const utterance=new SpeechSynthesisUtterance($('cardWord').textContent);utterance.lang='en-GB';utterance.rate=.82;utterance.pitch=1.04;if(voice)utterance.voice=voice;speechSynthesis.speak(utterance)};if(speechSynthesis.getVoices().length)speak();else speechSynthesis.onvoiceschanged=speak}
$('speakWord').onclick=e=>{e.stopPropagation();speakCurrentWord()};$('wordCard').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();$('wordCard').classList.toggle('flipped')}};
let lastQuizSignature='';
function shuffleCopy(items){return [...items].sort(()=>Math.random()-.5)}
function buildQuiz(){const source=[...currentUnit.words];if(source.length<20){$('quizHint').textContent='This unit needs at least 20 words for the checkpoint.';return}let selected,questions,bank,signature;do{selected=shuffleCopy(source).slice(0,20);questions=shuffleCopy(selected);bank=shuffleCopy(selected);signature=questions.map(w=>w.word).join('|')+'::'+bank.map(w=>w.word).join('|')}while(signature===lastQuizSignature);lastQuizSignature=signature;quizItems=questions.map(w=>({answer:w.word,prompt:(w.example||w.sourceExample||'').replace(w.word,'_____')}));$('wordBank').innerHTML=bank.map(w=>`<span class="bank-word">${w.word}</span>`).join('');$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><input class="answer-input" name="q${i}" autocomplete="off" spellcheck="false" placeholder="Type the missing word"></div>`).join('');$('quizProgressText').textContent='0 / 20 answered';$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}

function escapeHtml(value){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]))}
function escapeRegExp(value){return value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function makeQuizPrompt(w){const candidates=[w.sourceExample,w.example].filter(Boolean);const pattern=new RegExp('\\b'+escapeRegExp(w.word)+'\\b','i');for(const text of candidates){if(pattern.test(text))return text.replace(pattern,'_____')}return `This means "${w.definition}". The best word is _____.`}
function buildQuiz(){const source=[...currentUnit.words];if(source.length<20){$('quizHint').textContent='This unit needs at least 20 words for the checkpoint.';return}let selected,questions,bank,signature;do{selected=shuffleCopy(source).slice(0,20);questions=shuffleCopy(selected);bank=shuffleCopy(selected);signature=questions.map(w=>w.word).join('|')+'::'+bank.map(w=>w.word).join('|')}while(signature===lastQuizSignature);lastQuizSignature=signature;quizItems=questions.map(w=>({answer:w.word,prompt:makeQuizPrompt(w)}));$('wordBank').innerHTML=bank.map(w=>`<span class="bank-word">${w.word}</span>`).join('');$('quizQuestions').innerHTML=quizItems.map((q,i)=>`<div class="question"><b>QUESTION ${String(i+1).padStart(2,'0')}</b><p>${q.prompt}</p><input class="answer-input" name="q${i}" autocomplete="off" spellcheck="false" placeholder="Type the missing word"></div>`).join('');$('quizProgressText').textContent='0 / 20 answered';$('quizProgressBar').style.width='0%';clearInterval(timerId);timerId=setInterval(()=>{$('quizTimer').textContent=formatTime(Math.floor((Date.now()-learnStarted)/1000))},1000)}
async function submitQuiz(){const a=quizItems.map((_,i)=>document.querySelector(`input[name=q${i}]`));if(a.some(x=>!x||!x.value.trim())){$('quizHint').textContent='Please answer every question first.';return}if(new Set(a.map(x=>normAnswer(x.value))).size!==20){$('quizHint').textContent='Use each word from the bank once.';return}clearInterval(timerId);const correct=a.reduce((n,x,i)=>n+(normAnswer(x.value)===normAnswer(quizItems[i].answer)?1:0),0),score=Math.round(correct/20*100),seconds=Math.floor((Date.now()-learnStarted)/1000),record={name:currentName,unit:currentUnit.title,score,total:100,seconds,attempt:++attemptNo,passed:score>=70};const saved=await api('/api/attempts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(record)});if(!saved){const all=JSON.parse(localStorage.getItem('wordSprintAttempts')||'[]');all.unshift({...record,at:new Date().toLocaleString()});localStorage.setItem('wordSprintAttempts',JSON.stringify(all))}$('resultIcon').textContent=score>=70?'✓':'!';$('resultKicker').textContent=score>=70?'UNIT PASSED':'KEEP PRACTISING';$('resultTitle').textContent=score>=70?'You passed this round.':'Keep practising and try again.';$('resultScore').textContent=score;$('resultMessage').textContent=score>=70?`${currentName}, you have mastered this round's focus words.`:`You got ${correct} / 20. You need 70 points to pass.`;$('answerReview').innerHTML='<div class="review-title">ANSWER REVIEW</div>'+quizItems.map((q,i)=>{const student=a[i].value.trim(),ok=normAnswer(student)===normAnswer(q.answer);return `<div class="review-row ${ok?'correct':'wrong'}"><span>${String(i+1).padStart(2,'0')}</span><span>Your answer: <span class="review-answer">${escapeHtml(student)}</span></span><span class="review-correct">${ok?'Correct':'Correct: '+q.answer}</span></div>`}).join('');document.querySelector('.result-panel').classList.toggle('fail',score<70);show('resultView')}
$('retryBtn').onclick=()=>{wordIndex=0;learnStarted=Date.now();renderCard();show('learnView')};

// Teacher console sign-in. GitHub Pages can only provide a client-side gate;
// server.py should enforce the same credentials when deployed with the API.
const TEACHER_USERNAME='Julia Yuan';
const TEACHER_PASSWORD='yuanleleyuan0620';
$('teacherBtn').onclick=()=>{
  $('teacherUsername').value='';
  $('teacherPassword').value='';
  $('teacherLoginError').textContent='';
  show('teacherLoginView');
};
$('teacherLoginForm').onsubmit=async e=>{
  e.preventDefault();
  const username=$('teacherUsername').value.trim();
  const password=$('teacherPassword').value;
  if(username!==TEACHER_USERNAME || password!==TEACHER_PASSWORD){
    $('teacherLoginError').textContent='Incorrect username or password.';
    return;
  }
  show('teacherView');
  populateEditor();
  loadTeacher();
};
